### ISSUE TITLE
update to high quality streaming urls

### ISSUE THREAD

**Issue by ou-li** [glab84/plugin.audio.radio_data#2]
Another little suggestion:

192kbit/s AAC is now available:
https://community.roonlabs.com/t/new-fip-streaming-url/87335/7

**Comment by glab84** [comment]
Hello ou-li
I commit this change :
1) Replace logo with album cover in the summary, what do you think about this ?
2) Add fip Pop
3) Switch to high quality streaming AAC

**Comment by ou-li** [comment]
Beautiful! Working nicely here!

1 Album cover in the summary is nice when launching the plugin but it doesn't seem to get updated when I want so switch channels after a couple of minutes
2 👍🏽
3 👍🏽

I like the clear structure of your plugin. Makes it easy to figure out stuff as a python beginner. I might even try to add some more channels when I find the time.
