### ISSUE TITLE
Apostrophe toujours suivi d'une majuscule 

### ISSUE THREAD

**Issue by ou-li** [glab84/plugin.audio.radio_data#7]
Tu as une idée d'où ça peut venir?
![image4-600x](https://user-images.githubusercontent.com/7612981/139259057-db5ae4e4-7cad-4218-a888-a14c20a236c1.jpg)
![Screenshot_20211028-144750_Browser](https://user-images.githubusercontent.com/7612981/139259163-1e7b45dc-7423-4b89-996f-e07b597e2307.png)

**Comment by ou-li** [comment]
Top !

OT : As-tu une astuce pour bien configurer "fallback slideshow" ?
Y a-t-il une possibilité que Kodi télécharge automatiquement des images additionels comme il le fait pour la collection MP3 locale ?

**Comment by glab84** [comment]
L'idée du "fallback" : c'est de mettre le logo de la station dans un dossier, et en indiquant le même dans le paramétrage d"artist slideshow" pour qu'il affiche le logo quand il n'y a pas d'image d'artiste. Je n'ai pas testé depuis longtemps, pas sur que ca marche.
Tu as essayé : [le skin MQ8](https://forum.kodi.tv/showthread.php?tid=358382) ?
Sinon, je n'utilise pas les mp3.

**Comment by ou-li** [comment]
Merci pr les précisions !
Je vais essayer MQ8 dès que j'aurai un petit moment...
